import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/Layout/Header";
import Footer from "@/Layout/Footer";
import AddRandomContact from "@/components/AddRandomContact";
import RemoveAllContacts from "@/components/RemoveAllContacts";
import AddNewContact from "@/components/AddNewContact";
import FavouritesContacts from "@/components/FavouritesContacts";
import GeneralContacts from "@/components/GeneralContacts";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="border-2 border-orange-500 flex flex-col gap-y-4 items-center p-2 min-h-screen">
          <div className="flex flex-row gap-x-2">
            <div className="col-span-1 row-span-1 max-h-fit justify-self-end">
              <AddRandomContact />
            </div>
            <div className="col-span-1 row-span-1  justify-self-start">
              <RemoveAllContacts />
            </div>
          </div>
          <div className="w-full border-2 border-slate-200 rounded-md md:w-1/2 lg:w-3/4">
            <AddNewContact />
          </div>
          <div className="w-full bg-gray-600 rounded-md md:w-1/2 lg:w-3/4">
            <FavouritesContacts />
          </div>
          <div className="w-full bg-gray-800 rounded-md md:w-1/2 lg:w-3/4">
            <GeneralContacts />
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
