import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/Layout/Header";
import Footer from "@/Layout/Footer";
import AddRandomContact from "@/components/AddRandomContact";
import RemoveAllContacts from "@/components/RemoveAllContacts";
import AddNewContact from "@/components/AddNewContact";
import FavouritesContacts from "@/components/FavouritesContacts";
import GeneralContacts from "@/components/GeneralContacts";
import ContactsContainer from "@/components/base/wrapper/ContactsContainer";
import FormContainer from "@/components/base/wrapper/FormContainer";

const inter = Inter({ subsets: ["latin"] });

const contactFavouriteStyles =
  "w-full bg-gray-600 rounded-md md:w-1/2 lg:w-3/4";
const contactGeneralStyles = "w-full bg-slate-800 rounded-md md:w-1/2 lg:w-3/4";
const FormStyles =
  "w-full border-2 border-slate-200 rounded-md md:w-1/2 lg:w-3/4";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex flex-col gap-y-4 items-center p-2 min-h-screen">
          <div className="flex flex-row gap-x-2">
            <div className="justify-self-end">
              <AddRandomContact />
            </div>
            <div className="justify-self-start">
              <RemoveAllContacts />
            </div>
          </div>
          <FormContainer className={FormStyles}>
            <AddNewContact />
          </FormContainer>
          <ContactsContainer className={contactFavouriteStyles}>
            <FavouritesContacts />
          </ContactsContainer>
          <ContactsContainer className={contactGeneralStyles}>
            <GeneralContacts />
          </ContactsContainer>
        </div>
        <Footer />
      </main>
    </>
  );
}
